services:
  speakx-demo-app:
    image: rohan3004/speakx-demo-app:latest
    container_name: speakx-demo-app
    networks:
      - app_network
    expose:
      - 8080

  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - speakx-demo-app

networks:
  app_network:
    driver: bridge
