name: CI/CD Pipeline for Docker Compose to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to EC2 (using SSH) and deploy
    - name: Deploy to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

        # SSH into EC2 and deploy the application
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Ensure all necessary dependencies are installed
          sudo apt-get update -y
          
          # Install Git if not installed
          if ! command -v git &> /dev/null; then
            sudo apt-get install -y git
          fi

          # Install Docker if not installed
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi

          # Install Docker Compose if not installed
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          # Restart Docker to ensure it is running
          sudo systemctl restart docker

          # Clone or pull the latest changes from the repository
          REPO_URL="https://github.com/rohan3004/DevOps-Showcase.git"
          APP_DIR=~/app
          if [ -d "$APP_DIR" ]; then
            cd $APP_DIR
            git reset --hard
            git pull
          else
            git clone --depth 1 $REPO_URL $APP_DIR
            cd $APP_DIR
          fi

          # Run docker-compose up directly on the EC2 instance
          sudo docker-compose down
          sudo docker-compose up -d
        EOF
