# Terraform CI/CD Pipeline
name: Terraform Deployment

on:
  push:
    paths:
      - 'terraform/**'
    branches:
        - main
  workflow_dispatch:

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      # Step 3: Terraform Init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 4: Terraform Validate
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      # Step 5: Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
