name: Terraform Deployment

on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Authenticate Terraform Cloud
        env:
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
        run: echo "Terraform Cloud authenticated"

      # Step 3: Terraform Init
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_EC2_HOST: ${{ secrets.EC2_HOST }}  
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
        working-directory: ./terraform
        run: terraform init

      # Step 4: Terraform Validate
      - name: Terraform Validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_EC2_HOSTT: ${{ secrets.EC2_HOST }}  
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
        working-directory: ./terraform
        run: terraform validate

      # Step 5: Terraform Plan
      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_EC2_HOST: ${{ secrets.EC2_HOST }}  
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_EC2_HOST: ${{ secrets.EC2_HOST }} 
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }} 
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
